### ISSUE TITLE
Error when generating code from tag v1.1.0

### ISSUE THREAD

**Issue by dickerpulli** [adewg/ICAR#158]
I have problems generating java code out of the specs v.1.1.0. OpenAPI generator maven plugin (4.3.1) shows this error:

```
Caused by: java.lang.RuntimeException: Invalid inline schema defined in allOf in 'icarTreatmentProgramEventResource'. Per the OpenApi spec, for this case when a composed schema defines a discriminator, the allOf schemas must use $ref. Change this inline definition to a $ref definition
    at org.openapitools.codegen.DefaultCodegen.getAllOfDescendants (DefaultCodegen.java:2665)
    at org.openapitools.codegen.DefaultCodegen.createDiscriminator (DefaultCodegen.java:2722)
```

**Comment by dickerpulli** [comment]
OpenAPI generator maven plugin (4.2.3) does not work as well.

**Comment by cookeac** [comment]
Which version of the OpenAPI generator are you using? (It doesn't look like specifically a Maven plugin issue).
I'm struggling to see why it would be raising the issue for this particular case rather than others where we use allOf in the same way, but there is an OpenAPI generator bug 7262 that looks similar, and was fixed on 2 Sept 2020. Unless of course it is the nested oneOf that is confusing it.

**Comment by dickerpulli** [comment]
No, this is no maven plugin issue. I've also tried to use openapi-generator cli tool.

I have used the latest stable version of openapi-generator that is 4.3.1. I appended the console output:
[openapi-4.3.1.log](https://github.com/adewg/ICAR/files/5316236/openapi-4.3.1.log)

I also tried latest 4.2.x version that is 4.2.3. This also failed with this console output: 
[openapi-4.2.3.log](https://github.com/adewg/ICAR/files/5316237/openapi-4.2.3.log)

**Comment by ahokkonen** [comment]
Seems like there are unsupported use of nested "oneOf" definition inside "allOf". Not sure if it is against specs or bug in generator. I get the same with using v4.3.1

update: same with 5.0.0-beta2

**Comment by ghost** [comment]
I can confirm that. I extracted everything into its own type and still the same issue (even the "one of" part), so it has to be a general nesting issue with "allOf" and "oneOf". Has someone looked into alternatives to using "allOf" & friends? As the reference
https://json-schema.org/understanding-json-schema/reference/combining.html
states:

> This shortcoming is perhaps one of the biggest surprises of the combining operations in JSON schema: it does not behave like inheritance in an object-oriented language. There are some proposals to address this in the next version of the JSON schema specification.

I think at least for the eventResources we use the "allOf" like inheritance, don't we?

**Comment by ahokkonen** [comment]
yes, we use "allOf" for inheritance meaning, but seems like this is the first time "oneOf" is used for defining kind of generic type?
if "oneOf" is removed from scheme everything compiles well

**Comment by ghost** [comment]
I extracted the "oneOf" part into its own type and (for testing purposes) added it to a new type with a specific name for the field into another type. This worked then:

TreatmentProgramEventResource
```{
  "description": "An animal health event combining diagnosis and planned or actual treatment course or events.",
  "allOf": [
    {
      "$ref": "../resources/icarEventCoreResource.json"
    },
    {
      "$ref": "../types/newType.json"
    }
  ]
}
```

newType
```
{
  "type": "object",
  "properties": {
    "diagnoses": {
      "type": "array",
      "items": {
        "$ref": "../types/icarDiagnosisType.json"
      },
      "description": "Decribes the diagnosis of one or more conditions"
    },
    "whatever": {
      "$ref": "../types/icarOrType.json"
    }
  }
}
```

orType
```
{
  "type": "object",
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "courses": {
          "type": "array",
          "items": {
            "$ref": "../types/icarMedicineCourseSummaryType.json"
          },
          "description": "Details the course of treatments at a summary (start and end date) level. The array allows for different medicines/procedures."
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "treatments": {
          "type": "array",
          "items": {
            "$ref": "../resources/icarTreatmentEventResource.json"
          },
          "description": "The list of the treatments (medicines or procedures) applied."
        }
      }
    }
  ]
}
```

This _seems_ equivalent, but I'd propose to just remove "oneOf" and add fields for both exclusive types. The receiver/sender could decide which type to prefer. Also, is having both fields hurting anyone?

In general, the "oneOf" could result in a type hierarchy in OO (with no common fields etc.) to be able to provide both options in a single field, but I think this is not necessary. The generator does not create a type hierarchy, but it just adds the possibility to add both types of entities.

**Comment by cookeac** [comment]
I've been back through the JSON schema specs and guidelines, and it "looks" like it should be ok to combine allOf and oneOf as we have (there are some pretty esoteric examples!). I think this is why there is no Spectral linting error.

Similarly, despite the what the error message says, the actual OpenAPI spec doesn't seem to imply that both sides of an "allOf" (or "oneOf") must be $ref (with or without a discriminator as far as I can see). 

However, as 5.0.0 beta of the code generator doesn't seem to solve the issue, I think we need to be pragmatic.
The simplest solution is as @thomasd-gea  has suggested - we remove the "oneOf" and allow both an array of *treatments* **and** an array of *courses* (in addition to the array of *diagnoses*).

I'm not sure what it would **mean** to have both courses and treatments, so I recommend we also add a discriminator (probably should have had that already) so an API consumer knows whether they should be looking for courses or treatments.

**Comment by cookeac** [comment]
I went back and looked at the original *MLA Integrity Systems Company* work that treatments are based on, and there was discussion about the possible utility of having both courses and treatments, so decided that's another good argument to delete the "oneOf" and not implement a discriminator.
https://github.com/integritysystemscompany/animal_schema/issues/20
